telegram:
  bot:
    username: tendersalertbot
    token: 8403020132:AAG_OW8vDR_GxbGBCMXNEj3JuSQ7Iq49CYg

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_alert_bot?currentSchema=public
    username: postgres
    password: 123

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "Baseline Migration"
